# -*- coding: utf-8 -*-
"""NCERTV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DW1tHIWZ9C-9StNbF3j5yTdt_iD3o-DM
"""

!pip install langchain langchain-text-splitters langchain-community bs4

!pip install -qU langchain-huggingface

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

!pip install -U "langchain-core"

from langchain_core.vectorstores import InMemoryVectorStore

vector_store = InMemoryVectorStore(embeddings)

"""Indexing Started"""

!pip install pypdf

from langchain_community.document_loaders import PyPDFLoader

file_path = "ncert-9-1-30.pdf"
loader = PyPDFLoader(file_path)

docs = loader.load()
docs[0]

import pprint

pprint.pp(docs[0].metadata)

!pip install llama_parse

"""Chunking

To use LlamaParse, you need to provide your API key. Once you have set your `LLAMA_CLOUD_API_KEY` in Colab secrets, you can load it into your environment.
"""

import os
from google.colab import userdata

# Get the API key from Colab secrets
LLAMA_CLOUD_API_KEY = userdata.get('LLAMA_CLOUD_API_KEY')
os.environ["LLAMA_CLOUD_API_KEY"] = LLAMA_CLOUD_API_KEY

print("LLAMA_CLOUD_API_KEY loaded from Colab secrets.")

from llama_parse import LlamaParse
from langchain_text_splitters import (
    MarkdownHeaderTextSplitter,
    RecursiveCharacterTextSplitter
)


def parse_ncert_to_markdown(file_path: str) -> str:
    """
    Converts the NCERT PDF into clean Markdown using LlamaParse.
    This preserves the layout, tables, and structural headers.
    """
    print(f"Parsing {file_path} to Markdown...")
    parser = LlamaParse(
        result_type="markdown",  # Crucial for structural chunking
        verbose=True,
        language="en"
    )

    # Extract documents
    documents = parser.load_data(file_path)

    # Combine pages into a single markdown string
    full_markdown = "\n\n".join([doc.text for doc in documents])
    return full_markdown

def chunk_ncert_content(markdown_text: str):
    """
    Applies Structural Chunking followed by a Recursive Character Fallback.
    """
    # ---------------------------------------------------------
    # STEP 1: Structural Splitting (Document-Aware)
    # ---------------------------------------------------------
    # Define which Markdown headers we want to split on and what to name their metadata keys
    headers_to_split_on = [
        ("#", "Chapter"),
        ("##", "Main_Topic"),
        ("###", "Sub_Topic"),
        ('####', "Sub_Sub_Topic"),
        ("#####", "Sub_Sub_Sub_Topic")
    ]

    markdown_splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=headers_to_split_on,
        strip_headers=False # Keep the header in the chunk text for LLM context
    )

    # This creates chunks based purely on the semantic structure of the book
    structural_chunks = markdown_splitter.split_text(markdown_text)
    print(f"Generated {len(structural_chunks)} structural chunks.")

    # ---------------------------------------------------------
    # STEP 2: Recursive Fallback (Token/Character limitation)
    # ---------------------------------------------------------
    # If a section under a heading is massive, we break it down further.
    # Adjust chunk_size to match your embedding model's context window (e.g., 512 or 1024 tokens)
    recursive_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,     # Characters (approx 200-250 tokens)
        chunk_overlap=150,   # Preserve context across splits
        separators=["\n\n", "\n", ". ", " ", ""] # Hierarchical splitting
    )

    final_chunks = recursive_splitter.split_documents(structural_chunks)

    return final_chunks

if __name__ == "__main__":
    pdf_path = "ncert-9-1-30.pdf" # Replace with your file

    try:
        # 1. Parse
        md_content = parse_ncert_to_markdown(pdf_path)

        # 2. Chunk
        processed_chunks = chunk_ncert_content(md_content)

        # 3. Verify Output
        print(f"\nSuccessfully generated {len(processed_chunks)} final chunks suitable for embedding.")

        # Inspect a sample chunk to see the metadata inheritance
        if processed_chunks:
            sample = processed_chunks[2] # Grabbing a random chunk
            print("\n--- SAMPLE CHUNK ---")
            print(f"Metadata: {sample.metadata}")
            print(f"Content:\n{sample.page_content[:200]}...\n")

    except Exception as e:
        print(f"Error processing document: {e}")

# sample = processed_chunks[2] # Grabbing a random chunk
# print("\n--- SAMPLE CHUNK ---")
# print(f"Metadata: {sample.metadata}")
# print(f"Content:\n{sample.page_content[:200]}...\n")
print(processed_chunks[150])

!pip install rank_bm25

from rank_bm25 import BM25Okapi
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Download 'punkt_tab' resource
from nltk.tokenize import word_tokenize

# Prepare the corpus from processed_chunks
corpus = [chunk.page_content for chunk in processed_chunks]
tokenized_corpus = [word_tokenize(doc.lower()) for doc in corpus]

bm25 = BM25Okapi(tokenized_corpus)

query = "How to separate components from mixture"
tokenized_query = word_tokenize(query.lower())

doc_scores = bm25.get_scores(tokenized_query)

top_n = bm25.get_top_n(tokenized_query, corpus, n=3)

print(f"Query: {query}\n")
print("Top 3 similar documents:")
for i, doc in enumerate(top_n):
    print(f"\n--- Document {i+1} ---")
    print(doc)

!pip install langchain-classic

from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers import EnsembleRetriever
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore
import json

# ---------------------------------------------------------
# PREPARATION: Load your text chunks (using the already processed corpus)
# ---------------------------------------------------------
# 'corpus' is already available from the previous BM25 step

# ---------------------------------------------------------
# STEP 1: Initialize BM25 (The Keyword Brain)
# ---------------------------------------------------------
bm25_retriever = BM25Retriever.from_texts(corpus)
bm25_retriever.k = 5

# ---------------------------------------------------------
# STEP 2: Initialize Your Embeddings (The Semantic Brain)
# ---------------------------------------------------------
# 'embeddings' and 'vector_store' are already initialized globally.
# We just need to add the 'corpus' texts to the vector_store.
vector_store.add_documents(processed_chunks)

vector_retriever = vector_store.as_retriever(search_kwargs={"k": 5})

# ---------------------------------------------------------
# STEP 3: Fuse them with RRF
# ---------------------------------------------------------
hybrid_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, vector_retriever],
    weights=[0.4, 0.6] # 50/50 split of trust between keywords and semantics
)

# ==========================================
# Test the Retrieval
# ==========================================
if __name__ == "__main__":
    query = "What are allows?"

    final_docs = hybrid_retriever.invoke(query)

    print(f"Retrieved {len(final_docs)} chunks after fusion.\n")
    for i, doc in enumerate(final_docs, 1):
        print(f"--- Rank {i} ---")
        print(f"Content: {doc.page_content}...\n")

for i, doc in enumerate(final_docs, 1):
        print(f"--- Rank {i} ---")
        print(f"Content: {doc.page_content}...\n")

!pip install sentence-transformers

from sentence_transformers import CrossEncoder

# Load the cross-encoder model
reranker_model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

# Prepare pairs for re-ranking: (query, document_content)
candidate_pairs = [(query, doc.page_content) for doc in final_docs]

# Get scores from the re-ranker
sim_scores = reranker_model.predict(candidate_pairs)

# Pair the original documents with their scores and sort them
scored_docs = sorted(zip(sim_scores, final_docs), key=lambda x: x[0], reverse=True)

print("\n--- Re-ranked Documents (Cross-Encoder) ---")
for i, (score, doc) in enumerate(scored_docs, 1):
    print(f"--- Rank {i} (Score: {score:.4f}) ---")
    print(f"Content: {doc.page_content}...\n")

def retrieve_and_rerank_chunks(query: str):
    """
    Retrieves and re-ranks chunks based on a given query using hybrid retrieval and a cross-encoder.
    Returns at most the top 3 chunks with positive scores.
    """
    # 1. Hybrid Retrieval (BM25 + Vector Store)
    final_docs = hybrid_retriever.invoke(query)

    # 2. Re-ranking with Cross-Encoder
    candidate_pairs = [(query, doc.page_content) for doc in final_docs]
    sim_scores = reranker_model.predict(candidate_pairs)
    scored_docs = sorted(zip(sim_scores, final_docs), key=lambda x: x[0], reverse=True)

    # 3. Filter for positive scores and take top 3
    filtered_docs = []
    for score, doc in scored_docs:
        if score > 0:
            filtered_docs.append((score, doc))
        if len(filtered_docs) >= 3:
            break

    return filtered_docs

# Demonstrate the new function
demo_query = " Difference between homogeneous and heterogeneous"
relevant_chunks = retrieve_and_rerank_chunks(demo_query)

print(f"\n--- Top Re-ranked Chunks for Query: '{demo_query}' ---")
if relevant_chunks:
    for i, (score, doc) in enumerate(relevant_chunks, 1):
        print(f"--- Rank {i} (Score: {score:.4f}) ---")
        print(f"Content: {doc.page_content}\n")
else:
    print("No relevant chunks with positive scores found.")